AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BCO-DMO Frictionlessdata Data Package Pipeline

Parameters:
  Service:
    Type: String
    Description: The name of the service that we are deploying
  Environment:
    Type: String
    Description: Environment to which we are deploying (prod, stage, dev, etc)
  Bucket:
    Type: String
    Description: The S3 Bucket at which pipelines can be found.
  BcoDmoOfficeURI:
    Type: String
    Description: The Linked Data Identifier for the BCO-DMO Organization

Resources:
  Dpp2ProvAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true # sets for all methods
        UsagePlan:
          CreateUsagePlan: SHARED
  ToProv:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Service}-${Environment}-to-prov'
      Handler: lambda_handlers.to_prov
      Runtime: python3.7
      CodeUri: backend/
       Policies:
        - S3ReadPolicy:
            BucketName: !Ref Bucket
      MemorySize: 3008
      Timeout: 900
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          BUCKET: !Ref Bucket
          BCODMOOFFICEURI: !Ref BcoDmoOfficeURI
          LOG_LEVEL: INFO
      Events:
        HttpGet:
          Type: Api
          Properties:
            RestApiId: !Ref Dpp2ProvAPI
            Path: '/prov'
            Method: get
